### ISSUE TITLE
suggestion 2.0

### ISSUE THREAD

**Issue by populated** [Its-Vichy/GithubAccGenerator#4]
you could use https://mail.tm/en/ as a mail verification, since there api is free and you can easily scrape the code from the email.

**Comment by populated** [comment]
> you could use https://mail.tm/en/ as a mail verification, since there api is free and you can easily scrape the code from the email.

nevermind they have a gay header you cant grab 💀

**Comment by Its-Vichy** [comment]
I already have made wrapper for this website
